from django.contrib import admin
from django.urls import path
from frisbee_simulator_web.views import players, teams, tournaments, home, stats, users, games
from frisbee_simulator_web.views.about import AboutPageView
from frisbee_simulator_web.views.players import PlayerUpdateView
from frisbee_simulator_web.views.tournaments import TournamentDeleteView

urlpatterns = [
    path('', home.home, name='home'),
    path('admin/', admin.site.urls),
    path('login/', users.user_login, name='login'),
    path('register/', users.user_register, name='register'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('profile/view/', users.ProfileDetailView.as_view(), name='view_profile'),
    path('profile/edit/', users.ProfileEditView.as_view(), name='edit_profile'),
    path('logout/', users.user_logout, name='logout'),
    path('players/new/', players.PlayerCreateView.as_view(), name='create_player'),
    path('player/<int:pk>/edit/', PlayerUpdateView.as_view(), name='edit_player'),
    path('players/', players.list_players, name='list_players'),
    path('players/public/', players.list_players, kwargs={'is_public': True}, name='list_public_players'),
    path('players/detail/<int:pk>/', players.detail_player, name='detail_player'),
    path('teams/new/', teams.TeamCreateView.as_view(), name='create_team'),
    path('teams/random/', teams.random_team, name='random_team'),
    path('teams/', teams.list_teams, name='list_teams'),
    path('teams/public/', teams.list_teams, kwargs={'is_public': True}, name='list_public_teams'),
    path('teams/detail/<int:pk>/', teams.detail_team, name='detail_team'),
    path('pool_play/overview/<int:tournament_id>/', tournaments.pool_play_overview, name='pool_play_overview'),
    path('pool_play/manually_rank_teams_for_pool_play/<int:tournament_id>/',
         tournaments.manually_rank_teams_for_pool_play, name='manually_rank_teams_for_pool_play'),
    path('bracket/overview/<int:tournament_id>/', tournaments.bracket_overview, name='bracket_overview'),
    path('tournaments/simulate_game/<int:game_id>/<int:tournament_id>/', tournaments.simulate_game,
         name='simulate_game'),
    path('tournaments/new/', tournaments.TournamentCreateView.as_view(), name='create_tournament'),
    path('tournaments/', tournaments.list_tournaments, name='list_tournaments'),
    path('tournament/<int:pk>/delete/', TournamentDeleteView.as_view(), name='delete_tournament'),
    path('tournaments/public/', tournaments.list_tournaments, kwargs={'is_public': True},
         name='list_public_tournaments'),
    path('tournaments/detail/<int:pk>/', tournaments.detail_tournament, name='detail_tournament'),
    path('tournament/<int:tournament_id>/check_pool_play_simulation_status/',
         tournaments.check_pool_play_simulation_status,
         name='check_pool_play_simulation_status'),
    path('tournament/<int:tournament_id>/check_bracket_simulation_status/',
         tournaments.check_bracket_simulation_status,
         name='check_bracket_simulation_status'),
    path('tournament/<int:tournament_id>/fetch_latest_games_data/', tournaments.fetch_latest_games_data,
         name='fetch_latest_games_data'),
    # path('tournaments/simulate_bracket/<int:tournament_id>/', tournaments.simulate_bracket,
    #      name='simulate_bracket'),
    path('tournaments/simulate_tournament/<int:tournament_id>/', tournaments.simulate_tournament,
         name='simulate_tournament'),
    path('tournament/simulate_full_pool_play/<int:tournament_id>/', tournaments.simulate_full_pool_play,
         name='simulate_full_pool_play'),
    path('tournament/simulate_prequarterfinal_round/<int:tournament_id>/', tournaments.simulate_prequarterfinal_round,
         name='simulate_prequarterfinal_round'),
    path('tournament/simulate_quarterfinal_round/<int:tournament_id>/', tournaments.simulate_quarterfinal_round,
         name='simulate_quarterfinal_round'),
    path('tournament/simulate_semifinal_round/<int:tournament_id>/', tournaments.simulate_semifinal_round,
         name='simulate_semifinal_round'),
    path('tournament/simulate_final_round/<int:tournament_id>/', tournaments.simulate_final_round,
         name='simulate_final_round'),
    path('tournaments/results/<int:tournament_id>/', tournaments.tournament_results, name='tournament_results'),
    path('tournaments/results/four_team/<int:tournament_id>/', tournaments.four_team_tournament_results,
         name='four_team_tournament_results'),
    path('tournaments/results/eight_team/<int:tournament_id>/', tournaments.eight_team_tournament_results,
         name='eight_team_tournament_results'),
    path('tournaments/results/sixteen_team/<int:tournament_id>/', tournaments.sixteen_team_tournament_results,
         name='sixteen_team_tournament_results'),
    path('tournaments/pool_play_results/<int:tournament_id>/', tournaments.pool_play_results, name='pool_play_results'),
    path('games/detail/<int:pk>/', tournaments.detail_game, name='detail_game'),
    path('points/detail/<int:pk>/', tournaments.detail_point, name='detail_point'),
    path('stats/list_player_tournament_stats/<int:tournament_id>/', stats.list_player_tournament_stats,
         name='list_player_tournament_stats'),
    path('stats/detail_player_tournament_stats/<int:tournament_id>/<int:player_id>/',
         stats.detail_player_tournament_stats, name='detail_player_tournament_stats'),
    path('games/simulate_individual_game/<int:game_id>/', games.simulate_individual_game,
         name='simulate_individual_game'),
    path('games/create_individual_game/', games.create_individual_game, name='create_individual_game'),
    path('games/games_list/', games.games_list, name='games_list')
]
