# Generated by Django 4.2.7 on 2023-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='simulation_type',
            field=models.CharField(choices=[(4, '4'), (8, '8'), (16, '16'), (20, '20'), (32, '32')], default='player_rating'),
        ),
    ]
