# Generated by Django 4.2.7 on 2024-01-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket_play_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pool_play_completed',
            field=models.BooleanField(default=False),
        ),
    ]
