# Generated by Django 4.2.7 on 2023-12-10 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0002_tournament_simulation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='deep_cut_defense',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deep_cut_offense',
        ),
        migrations.AddField(
            model_name='player',
            name='deep_huck_cut_defense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='player',
            name='deep_huck_cut_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='player',
            name='short_huck_cut_defense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='player',
            name='short_huck_cut_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='deep_huck_throw_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='handle_cut_defense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='handle_cut_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='handle_mark_defense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_huck_throw_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='swing_throw_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='under_cut_defense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='under_cut_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='under_throw_offense',
            field=models.PositiveIntegerField(default=65, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='simulation_type',
            field=models.CharField(choices=[('player_rating', 'player_rating'), ('team_rating', 'team_rating')], default='player_rating'),
        ),
    ]
