# Generated by Django 4.2.7 on 2024-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0003_alter_tournament_number_of_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
