# Generated by Django 4.2.7 on 2023-12-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0003_remove_player_deep_cut_defense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergamestat',
            old_name='hucks_completed',
            new_name='deep_hucks_completed',
        ),
        migrations.RenameField(
            model_name='playergamestat',
            old_name='hucks_thrown',
            new_name='deep_hucks_thrown',
        ),
        migrations.RenameField(
            model_name='playergamestat',
            old_name='passes_completed',
            new_name='short_hucks_completed',
        ),
        migrations.RenameField(
            model_name='playergamestat',
            old_name='passes_thrown',
            new_name='short_hucks_thrown',
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='swing_passes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='swing_passes_thrown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='under_passes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='under_passes_thrown',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
