# Generated by Django 4.2.7 on 2024-02-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0004_game_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pool_play_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
