# Generated by Django 4.2.7 on 2024-01-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0004_alter_profile_date_of_birth_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary_line',
            field=models.CharField(choices=[('OFFENSE', 'OFFENSE'), ('DEFENSE', 'DEFENSE'), ('BENCH', 'BENCH')], max_length=50, null=True),
        ),
    ]
