# Generated by Django 4.2.7 on 2024-01-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0005_player_primary_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='height',
            new_name='height_in_inches',
        ),
    ]
