# Generated by Django 4.2.7 on 2024-02-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0005_tournament_bracket_initialized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket_games',
            field=models.ManyToManyField(related_name='bracket_games_tournament', to='frisbee_simulator_web.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pool_play_games',
            field=models.ManyToManyField(related_name='pool_play_games_tournament', to='frisbee_simulator_web.game'),
        ),
    ]
