# Generated by Django 4.2.7 on 2023-12-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0005_rename_hucks_completed_playertournamentstat_deep_hucks_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestat',
            name='throwaways',
        ),
    ]
