# Generated by Django 4.2.7 on 2023-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0006_remove_playergamestat_throwaways'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='throwaways',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
