# Generated by Django 4.2.7 on 2024-01-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0006_rename_height_player_height_in_inches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='weight',
            new_name='weight_in_lbs',
        ),
    ]
