# Generated by Django 4.2.7 on 2023-12-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0007_playergamestat_throwaways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestat',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='throwing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playertournamentstat',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playertournamentstat',
            name='throwing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='total_receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestat',
            name='total_throwing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtournamentstat',
            name='passing_yards_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtournamentstat',
            name='passing_yards_for',
            field=models.IntegerField(default=0),
        ),
    ]
