# Generated by Django 4.2.7 on 2024-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0007_remove_tournament_bracket_games_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='bracket_initialized',
            new_name='final_round_initialized',
        ),
        migrations.AddField(
            model_name='tournament',
            name='semifinal_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
