# Generated by Django 4.2.7 on 2024-02-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0008_rename_bracket_initialized_tournament_final_round_initialized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='semifinal_initialized',
            new_name='semifinal_round_initialized',
        ),
    ]
