# Generated by Django 4.2.7 on 2024-01-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0008_alter_team_location_alter_team_mascot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile'),
        ),
        migrations.AlterField(
            model_name='season',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.profile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_teams',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (20, '20'), (32, '32')], default=4),
        ),
    ]
