# Generated by Django 4.2.7 on 2024-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0009_alter_game_created_by_alter_player_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='print_statements',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Pool Play', 'Pool Play'), ('Pre-Quarterfinal', 'Pre-Quarterfinal'), ('Quarterfinal', 'Quarterfinal'), ('Loser-Semifinal', 'Loser-Semifinal'), ('Fifth-Place-Final', 'Fifth-Place-Final'), ('Seventh-Place-Final', 'Seventh-Place-Final'), ('Semifinal', 'Semifinal'), ('Championship', 'Championship'), ('9th-Place Quarterfinal', '9th-Place Quarterfinal'), ('13th-Place Semifinal', '13th-Place Semifinal'), ('15th-Place Final', '15th-Place Final'), ('9th-Place Semifinal', '9th-Place Semifinal'), ('11th-Place Final', '11th-Place Final'), ('9th-Place Final', '9th-Place Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_teams',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16')], default=4),
        ),
    ]
