# Generated by Django 4.2.7 on 2023-12-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0009_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPointStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('swing_passes_thrown', models.PositiveIntegerField(default=0)),
                ('swing_passes_completed', models.PositiveIntegerField(default=0)),
                ('under_passes_thrown', models.PositiveIntegerField(default=0)),
                ('under_passes_completed', models.PositiveIntegerField(default=0)),
                ('short_hucks_thrown', models.PositiveIntegerField(default=0)),
                ('short_hucks_completed', models.PositiveIntegerField(default=0)),
                ('deep_hucks_thrown', models.PositiveIntegerField(default=0)),
                ('deep_hucks_completed', models.PositiveIntegerField(default=0)),
                ('throwing_yards', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('turnovers_forced', models.PositiveIntegerField(default=0)),
                ('throwaways', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('callahans', models.PositiveIntegerField(default=0)),
                ('pulls', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_stats', to='frisbee_simulator_web.player')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='frisbee_simulator_web.point')),
            ],
        ),
    ]
