# Generated by Django 4.2.7 on 2024-02-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0009_rename_semifinal_initialized_tournament_semifinal_round_initialized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='bracket_play_completed',
            new_name='final_round_completed',
        ),
        migrations.AddField(
            model_name='tournament',
            name='semifinal_round_completed',
            field=models.BooleanField(default=False),
        ),
    ]
