# Generated by Django 4.2.7 on 2024-02-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0010_rename_bracket_play_completed_tournament_final_round_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='quarterfinal_round_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='quarterfinal_round_games',
            field=models.ManyToManyField(related_name='quarterfinal_games_tournament', to='frisbee_simulator_web.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='quarterfinal_round_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
