# Generated by Django 4.2.7 on 2024-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0010_game_print_statements_alter_game_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='print_statements',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
