# Generated by Django 4.2.7 on 2023-12-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0010_playerpointstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_number_in_game',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
