# Generated by Django 4.2.7 on 2024-02-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0011_tournament_quarterfinal_round_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpool',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Pool Play', 'Pool Play'), ('Pre-Quarterfinal', 'Pre-Quarterfinal'), ('Quarterfinal', 'Quarterfinal'), ('Loser-Semifinal', 'Loser-Semifinal'), ('5th-Place-Final', '5th-Place-Final'), ('7th-Place-Final', '7th-Place-Final'), ('Semifinal', 'Semifinal'), ('3rd-Place', 'Third-Place'), ('Championship', 'Championship'), ('9th-Place Quarterfinal', '9th-Place Quarterfinal'), ('13th-Place Semifinal', '13th-Place Semifinal'), ('15th-Place Final', '15th-Place Final'), ('9th-Place Semifinal', '9th-Place Semifinal'), ('11th-Place Final', '11th-Place Final'), ('9th-Place Final', '9th-Place Final')], max_length=50),
        ),
    ]
