# Generated by Django 4.2.7 on 2024-01-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0011_alter_game_print_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='print_statements',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
