# Generated by Django 4.2.7 on 2023-12-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0012_rename_playerpointstats_playerpointstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stats_for_tournament', to='frisbee_simulator_web.tournament'),
        ),
        migrations.AddField(
            model_name='playerpointstat',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_stats_for_game', to='frisbee_simulator_web.game'),
        ),
    ]
