# Generated by Django 4.2.7 on 2024-02-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0012_tournamentpool_name_alter_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='losers_final_round_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_final_round_games',
            field=models.ManyToManyField(related_name='losers_final_games_tournament', to='frisbee_simulator_web.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_final_round_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_quarterfinal_round_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_quarterfinal_round_games',
            field=models.ManyToManyField(related_name='losers_quarterfinal_games_tournament', to='frisbee_simulator_web.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_quarterfinal_round_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_semifinal_round_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_semifinal_round_games',
            field=models.ManyToManyField(related_name='losers_semifinal_games_tournament', to='frisbee_simulator_web.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losers_semifinal_round_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
