# Generated by Django 4.2.7 on 2024-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0012_point_print_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='team_one_score_post_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='team_two_score_post_point',
            field=models.IntegerField(default=0),
        ),
    ]
