# Generated by Django 4.2.7 on 2024-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0013_point_team_one_score_post_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='print_statements',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
