# Generated by Django 4.2.7 on 2024-02-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0013_tournament_losers_final_round_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Pool Play', 'Pool Play'), ('Pre-Quarterfinal', 'Pre-Quarterfinal'), ('Quarterfinal', 'Quarterfinal'), ('5th-Place Semifinal', 'Loser-Semifinal'), ('5th-Place Final', '5th-Place-Final'), ('7th-Place Final', '7th-Place-Final'), ('Semifinal', 'Semifinal'), ('3rd-Place Final', 'Third-Place'), ('Championship', 'Championship'), ('9th-Place Quarterfinal', '9th-Place Quarterfinal'), ('13th-Place Semifinal', '13th-Place Semifinal'), ('15th-Place Final', '15th-Place Final'), ('9th-Place Semifinal', '9th-Place Semifinal'), ('11th-Place Final', '11th-Place Final'), ('9th-Place Final', '9th-Place Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_teams',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16')], default=4),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='number_of_teams',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16')], default=4),
        ),
    ]
