# Generated by Django 4.2.7 on 2024-03-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0014_alter_game_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.tournamentpool'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Pool Play', 'Pool Play'), ('Pre-Quarterfinal', 'Pre-Quarterfinal'), ('Quarterfinal', 'Quarterfinal'), ('Semifinal', 'Semifinal'), ('Championship', 'Championship'), ('3rd-Place Final', '3rd-Place Final'), ('5th-Place Semifinal', '5th-Place Semifinal'), ('5th-Place Final', '5th-Place Final'), ('7th-Place Final', '7th-Place Final'), ('9th-Place Quarterfinal', '9th-Place Quarterfinal'), ('9th-Place Semifinal', '9th-Place Semifinal'), ('9th-Place Final', '9th-Place Final'), ('11th-Place Final', '11th-Place Final'), ('13th-Place Semifinal', '13th-Place Semifinal'), ('13th-Place Final', '13th-Place Final'), ('15th-Place Final', '15th-Place Final')], max_length=50),
        ),
    ]
