# Generated by Django 4.2.7 on 2024-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0014_alter_game_print_statements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='print_statements',
        ),
        migrations.AlterField(
            model_name='point',
            name='print_statements',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
