# Generated by Django 4.2.7 on 2024-01-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0015_rename_team_two_game_away_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='home_team',
            new_name='team_one',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='away_team',
            new_name='team_two',
        ),
    ]
