# Generated by Django 4.2.7 on 2024-01-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0015_remove_game_print_statements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='print_statements',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
