# Generated by Django 4.2.7 on 2024-03-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0015_game_pool_alter_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bracket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee_simulator_web.tournamentbracket'),
        ),
    ]
