# Generated by Django 4.2.7 on 2024-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0016_alter_point_print_statements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='print_statements',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
