# Generated by Django 4.2.7 on 2024-03-27 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0018_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestat',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stats_for_tournament', to='frisbee_simulator_web.tournament'),
        ),
    ]
