# Generated by Django 4.2.7 on 2024-04-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0019_alter_playergamestat_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prequarter_final_round_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prequarter_final_round_games',
            field=models.ManyToManyField(related_name='prequarter_final_games_tournament', to='frisbee_simulator_web.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prequarter_final_round_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
