# Generated by Django 4.2.7 on 2024-04-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0020_tournament_prequarter_final_round_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='prequarter_final_round_completed',
            new_name='pre_quarterfinal_round_completed',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='prequarter_final_round_games',
            new_name='pre_quarterfinal_round_games',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='prequarter_final_round_initialized',
            new_name='pre_quarterfinal_round_initialized',
        ),
    ]
