# Generated by Django 4.2.7 on 2024-04-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0022_tournament_pool_play_seeds_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='set_pool_play_seeds_manually',
        ),
    ]
