# Generated by Django 4.2.7 on 2024-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee_simulator_web', '0023_remove_tournament_set_pool_play_seeds_manually'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pool_play_games_completed_counter',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pool_play_total_number_of_games',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
